<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'آدرس',
    'Are you sure you want to delete this item?' => 'آیا از حذف این مورد مطمئن هستید؟',
    'Auth Key' => '',
    'Battery Voltage' => '',
    'Bind To Ip' => '',
    'Change own password' => 'تغییر رمز ورود',
    'Command1' => '',
    'Command2' => '',
    'Confirmation Token' => '',
    'Course' => '',
    'Create' => 'ایجاد',
    'Create Device' => 'ایجاد دستگاه',
    'Create Device Config' => '',
    'Create Location Info' => 'ایجاد اطلاعات مکانی',
    'Create User Device' => '',
    'Created At' => 'زمان ایجاد',
    'Delete' => 'حذف',
    'Device' => 'دستگاه',
    'Device Configs' => '',
    'Device ID' => '',
    'Device List' => 'لیست دستگاه',
    'Devices' => 'لیست دستگاه',
    'Door' => '',
    'Email' => 'ایمیل',
    'Email Confirmed' => '',
    'From Date' => 'از تاریخ',
    'Frontend' => '',
    'ID' => '',
    'Last location info' => 'اطلاعات آخرین موقعیت',
    'Latitude' => '',
    'Location Infos' => 'لیست اطلاعات مکانی',
    'Logout' => 'خروج',
    'Longitude' => '',
    'Motor' => '',
    'Name' => 'نام',
    'No' => '',
    'No Data!' => 'اطلاعاتی یافت نشد!',
    'Password Hash' => '',
    'Please select a device!' => 'لطفا یک دستگاه را انتخاب نمایید!',
    'Province ID' => '',
    'Registration Ip' => '',
    'Request' => '',
    'Reset' => '',
    'Save' => 'ذخیره',
    'Search' => 'جستجو',
    'Select Device' => 'انتخاب دستگاه',
    'Select User' => 'انتخاب کاربر',
    'Serial' => 'شماره سریال',
    'Shock Sensor' => '',
    'Sim Number' => 'شماره سیم کارت',
    'Speed' => 'سرعت',
    'Superadmin' => '',
    'The requested page does not exist.' => '',
    'Time' => 'زمان',
    'To Date' => 'تا تاریخ',
    'Trace' => '',
    'Trace System' => '',
    'Tracer System' => 'سیستم ردیابی',
    'Update' => 'ویرایش',
    'Update Location Info: {nameAttribute}' => '',
    'Update User Device: {nameAttribute}' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'User' => 'کاربر',
    'User Device' => 'تخصیص دستگاه به کاربر',
    'User Devices' => 'لیست دستگاه های کاربران',
    'User ID' => '',
    'User Management' => '',
    'User Name' => '',
    'User Phone' => '',
    'User Status' => '',
    'Username' => '',
    'Yes' => '',
];
